name: Test API Prediction Sentiment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    # Étape 1 : Configuration de l'environnement
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # Étape 2 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m venv myenv
        .\myenv\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 3 : Télécharger les données NLTK
    - name: Download NLTK Data
      run: |
        .\myenv\Scripts\activate
        python -m nltk.downloader punkt wordnet omw-1.4 stopwords
      env:
        NLTK_DATA: ${{ runner.temp }}/nltk_data


    # Étape 4 : Lancer l'API FastAPI avec PowerShell sur le port 8080
    - name: Run FastAPI app
      run: |
        .\myenv\Scripts\activate
        Start-Process "uvicorn" -ArgumentList "API_prediction_sentiment:app --host 0.0.0.0 --port 8080 --reload"

    # Étape 5 : Lancer les tests unitaires immédiatement après le démarrage de l'API
    - name: Run FastAPI tests
      run: |
        .\myenv\Scripts\activate
        pytest test_API_prediction_sentiment.py --disable-warnings

    # Étape 6 : Lancer l'application Streamlit pour les tests manuels (optionnel)
    - name: Run Streamlit app (optional for manual testing)
      run: |
        .\myenv\Scripts\activate
        streamlit run test_API_prediction_sentiment.py
      continue-on-error: true
