name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: sentiments-predict                # set this to the name of your Azure Web App
  PYTHON_VERSION: '3.12'                               # set this to the Python version to use

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 : Check-out du dépôt
      - name: Check out repository
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Étape 3 : Vider le cache Python
      - name: Clear Python cache
        shell: cmd
        run: |
          if exist __pycache__ rmdir /S /Q __pycache__
          for /D %%d in (myenv) do if exist %%d (rmdir /S /Q %%d)
          echo "Cache cleared."

      # Étape 4 : Création de l'environnement virtuel et installation des dépendances
      - name: Set up virtual environment and install dependencies
        shell: cmd
        run: |
          python -m venv myenv
          myenv\Scripts\activate && python -m pip install --upgrade pip && pip install -r requirements.txt

      # Étape 5 : Télécharger les données NLTK
      - name: Download NLTK Data
        shell: cmd
        run: |
          myenv\Scripts\activate && python -c "import nltk; nltk.download('punkt'); nltk.download('wordnet'); nltk.download('omw-1.4'); nltk.download('stopwords')"

      # Étape 6 : Lancer l'API FastAPI dans un processus distinct
      - name: Run FastAPI app in the background
        shell: cmd
        run: |
          myenv\Scripts\activate && python run_api.py

      # Étape 7 : Lancer les tests unitaires pour vérifier l'API
      - name: Run API unit tests
        shell: cmd
        run: |
          myenv\Scripts\activate && pytest test_API_prediction_sentiment.py --disable-warnings

      # Étape 8 : Terminer le processus uvicorn après les tests
      - name: Kill uvicorn process
        shell: cmd
        run: |
          taskkill /F /IM uvicorn.exe

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}