name: Test API on Windows (GitHub Actions)

on:
  push:
    branches:
      - main  # Déclencher le workflow sur push vers la branche main
  workflow_dispatch:  # Permet de lancer le workflow manuellement

jobs:
  test:
    runs-on: windows-latest  # Utiliser un environnement Windows

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Configurer l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Lancer l'API en arrière-plan
      - name: Start API
        run: |
          python API_p7_Reglog.py &  # Lancer l'API en arrière-plan
        shell: cmd

      # Étape 5 : Ajouter un délai pour s'assurer que l'API est démarrée
      - name: Wait for API to start
        run: timeout /t 10  # Attendre 10 secondes pour que l'API démarre

      # Étape 6 : Exécuter les tests unitaires
      - name: Run Unit Tests
        run: |
          python -m unittest test_Api_LogReg_P7.py

      # Étape 7 : Tester les endpoints de l'API avec des requêtes HTTP
      - name: Test API Endpoints
        run: |
          python test_api_with_requests.py
