name: Test API Prediction Sentiment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Étape 1 : Check-out du dépôt
      - name: Check out repository
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Étape 3 : Création de l'environnement virtuel et installation des dépendances
      - name: Set up virtual environment and install dependencies
        shell: cmd
        run: |
          python -m venv myenv
          myenv\Scripts\activate && python -m pip install --upgrade pip && pip install -r requirements.txt

      # Étape 4 : Télécharger les données NLTK
      - name: Download NLTK Data
        shell: cmd
        run: |
          myenv\Scripts\activate && python -c "import nltk; nltk.download('punkt'); nltk.download('wordnet'); nltk.download('omw-1.4'); nltk.download('stopwords')"

      # Étape 5 : Lancer l'API FastAPI dans un processus distinct
      - name: Run FastAPI app in the background
        shell: cmd
        run: |
          myenv\Scripts\activate && python run_api.py

      # Étape 6 : Lancer les tests unitaires pour vérifier l'API
      - name: Run API unit tests
        shell: cmd
        run: |
          myenv\Scripts\activate && pytest test_API_prediction_sentiment.py --disable-warnings

      # Étape 7 : Terminer le processus uvicorn après les tests
      - name: Kill uvicorn process
        shell: cmd
        run: |
          taskkill /F /IM uvicorn.exe
