name: Test API Prediction Sentiment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    # Étape 1 : Configuration de l'environnement
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # Étape 2 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m venv myenv
        .\myenv\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 3 : Lancer l'API FastAPI
    - name: Run FastAPI app
      run: |
        .\myenv\Scripts\activate
        nohup uvicorn script_name:app --host 0.0.0.0 --port 8001 --reload &

    # Étape 4 : Attendre que l'API démarre (ajoute un délai d'attente)
    - name: Wait for FastAPI to start
      run: |
        sleep 10  # Attendre 10 secondes pour s'assurer que l'API est prête

    # Étape 5 : Lancer les tests unitaires
    - name: Run FastAPI tests
      run: |
        .\myenv\Scripts\activate
        pytest test_API_prediction_sentiment.py --disable-warnings

    # Étape 6 : Lancer l'application Streamlit pour les tests manuels (optionnel)
    - name: Run Streamlit app (optional for manual testing)
      run: |
        .\myenv\Scripts\activate
        streamlit run test_API_prediction_sentiment.py
      continue-on-error: true
