name: Test API Prediction Sentiment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    # Étape 1 : Configuration de l'environnement
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Set up virtual environment and install dependencies
      run: |
        python -m venv myenv
        .\myenv\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt
      env:
        NLTK_DATA: ${{ runner.temp }}/nltk_data

    # Étape 2 : Télécharger les données NLTK
    - name: Download NLTK Data
      run: |
        .\myenv\Scripts\activate
        python -c "import nltk; \
                   nltk.download('punkt', download_dir='${{ runner.temp.replace('\\', '/') }}/nltk_data'); \
                   nltk.download('wordnet', download_dir='${{ runner.temp.replace('\\', '/') }}/nltk_data'); \
                   nltk.download('omw-1.4', download_dir='${{ runner.temp.replace('\\', '/') }}/nltk_data'); \
                   nltk.download('stopwords', download_dir='${{ runner.temp.replace('\\', '/') }}/nltk_data')"
      env:
        NLTK_DATA: ${{ runner.temp }}/nltk_data

    # Étape 3 : Lancer l'API FastAPI sur le port 8080
    - name: Run FastAPI app
      run: |
        .\myenv\Scripts\activate
        uvicorn API_prediction_sentiment:app --host 127.0.0.1 --port 8080 --reload &
      env:
        NLTK_DATA: ${{ runner.temp }}/nltk_data

    # Étape 4 : Lancer les tests unitaires pour l'API
    - name: Run API unit tests
      run: |
        .\myenv\Scripts\activate
        pytest test_API_prediction_sentiment.py --disable-warnings

    # Étape 5 : Lancer l'application Streamlit
    - name: Run Streamlit app
      run: |
        .\myenv\Scripts\activate
        streamlit run streamlit_dashboard_P7.py --server.port=8502 &
      env:
        STREAMLIT_SERVER_PORT: 8502

    # Étape 6 : Tester si l'application Streamlit est accessible
    - name: Test Streamlit app
      run: |
        sleep 10  # Attendre quelques secondes pour s'assurer que l'application démarre
        curl -f http://127.0.0.1:8502
