name: Test API Prediction Sentiment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    # Étape 1 : Check-out du dépôt
    - name: Check out repository
      uses: actions/checkout@v3

    # Étape 2 : Configuration de Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # Étape 3 : Configuration de l'environnement virtuel et installation des dépendances
    - name: Set up virtual environment and install dependencies
      run: |
        python -m venv myenv
        myenv\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt
      env:
        NLTK_DATA: ${{ runner.temp }}/nltk_data

    # Étape 4 : Télécharger les données NLTK
    - name: Download NLTK Data
      run: |
        myenv\Scripts\activate
        python -c "import nltk; \
                   nltk.download('punkt', download_dir='${{ runner.temp.replace('\\', '/') }}/nltk_data'); \
                   nltk.download('wordnet', download_dir='${{ runner.temp.replace('\\', '/') }}/nltk_data'); \
                   nltk.download('omw-1.4', download_dir='${{ runner.temp.replace('\\', '/') }}/nltk_data'); \
                   nltk.download('stopwords', download_dir='${{ runner.temp.replace('\\', '/') }}/nltk_data')"
      env:
        NLTK_DATA: ${{ runner.temp }}/nltk_data

    # Étape 5 : Lancer les tests unitaires (sans lancer FastAPI)
    - name: Run API unit tests
      run: |
        myenv\Scripts\activate
        pytest test_API_prediction_sentiment.py --disable-warnings
